---
version: 3.8
services:
    wordpress:
        environment:
            # Uses client_host for v3, and remote_host for v2 depending on PHP version.
            XDEBUG_CONFIG: client_host=${IP} remote_host=${IP}
