---
version: 3.8
services:
    memcached:
        image: memcached:latest
        networks:
            - wp
    redis:
        image: redis:latest
        volumes:
            - redis_data:/data
        networks:
            - wp

# All volumes used for this service
volumes:
    redis_data: {}

networks:
    wp: {}
